conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm
from django.conf.urls.static import static
from django.conf import settings


app_name='core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('task/', views.check_form, name='task'),
    path('about/', views.about, name='about') ,
    path('terms/', views.term_of_use, name='terms'),
    path('privacy/', views.privacy, name='privacy'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm), name='login')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoProject5/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('core.urls')),
    # path('task/',include('core.urls')),
    path('items/', include('item.urls')),
    path('inbox/', include('conversation.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path

from . import views

app_name = 'item'
urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),

]

core/models.py
from django.db import models

# class Task(models.Model):
#     title = models.CharField("Название", max_length=50)
#     task = models.TextField('Описание')
#     def __str__(self):
#         return self.title
#
#     class Meta:
#         verbose_name = 'Задача'
#         verbose_name_plural = 'Задачи'

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))


class TaskForm(forms.Form):
    a = forms.FloatField(label='параметр')

core/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# from core.forms import TaskForm
from item.models import Category, Item
from .forms import SignUpForm, TaskForm


def index(request):
    items = Item.objects.filter(is_sold=False)
    categories = Category.objects.all()
    paginator = Paginator(items, 3)
    page = request.GET.get('page')
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)

    return render(request, 'core/index.html',
                  {'categories': categories,
                   'items': items,}
                  )


def contact(request):
    return render(request, 'core/contact.html')


def privacy(request):
    return render(request, 'core/privacy.html')


def term_of_use(request):
    return render(request, 'core/terms.html')


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignUpForm()

    return render(request, 'core/signup.html', {
        'form': form
    })


def check_form(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            a = form.cleaned_data['a']
            return solution(request, a)
    else:
        form = TaskForm()

    context = {'form': form}
    return render(request, 'core/task.html', context)


# Дано вещественное число A. Вычислить x = 0 при a > 100; x = a при a < 61, в противном случае x = a**4.
def solution(request, a):
    if a > 100:
        ans = 0
    elif a < 61:
        ans = a
    else:
        ans = a ** 4

    context = {'answer': ans, 'question': a}
    return render(request, 'core/answer.html', context)


def about(request):
    context = {
        'my': {
            'name': 'Мурадханова Полина Раджабалиевна',
            'phone': '+79679425833',
            'mail': 'prmuradkhanova@edu.hse.ru',
            'imgurl': 'https://n1s1.hsmedia.ru/be/1b/1b/be1b1bb5f29c51f945d361ea86348a4d/332x332_1_37e481a1cec03d2c0406a1f8e071ea13@415x415_0xac120003_3151271871596024352.jpg'
        },
        'program': {
            'name': 'Экономика',
            'description': 'Образовательная программа «Экономика»  сочетает фундаментальную подготовку студентов в области теоретической и прикладной экономики и финансов с проектно-ориентированным обучением, дающим практические навыки, обеспечивающие выпускникам преимущества в трудоустройстве и гарантирующие профессиональный рост. ',
            'ruk': {
                'name': 'Кирилл Александрович Букин',
                'mail': 'kabukin@hse.ru',
                'imgurl':'https://www.hse.ru/pubs/share/thumb/187225977:c2103x2103+50+0:r380x380!.jpg'
            },
            'man': {
                'name': 'Макарова Галина Викторовна',
                'mail': 'gvmakarova@hse.ru',
                'imgurl':'https://www.hse.ru/pubs/share/thumb/223562260:c527x527+93+0:r380x380!.jpg'
            }
        },
        'pal1': {
            'name': 'Ушатова Арина Юрьевна',
            'phone': '+79000000000',
            'mail': 'ayuushatova@edu.hse.ru',
            'imgurl': 'https://avatars.dzeninfra.ru/get-zen_doc/3724792/pub_603e34c38da63757af6856a7_60a7bc2857455d23caa3d214/scale_720'
        },
        'pal2': {
            'name': 'Зорина Лина Юрьевна',
            'phone': '+79111111111',
            'mail': 'luzorina@edu.hse.ru',
            'imgurl': 'https://n1s2.hsmedia.ru/80/89/18/8089181c9788e14eb451a3eca4d26d72/418x600_1_e1785549b61ac612388792a31281d65b@486x698_0xac120003_15674663381613017379.jpg'
        },
    }
    return render(request, 'core/about.html', context)

core/templates/core/about.html
{% extends 'core/base.html' %}

{% block title %}About Us{% endblock %}
{% block content %}
    <div style="text-align: center;">
        <style>
            .header-h1 {
                text-align: center;
            }
            .header-h1 h1 {
                display: inline-block;
                background: #0097a7;
                color: #fff;
                margin-bottom: 0;
                padding: .5rem 1rem .625rem 1rem;
                font-size: 1.5rem;
                text-transform: uppercase;
                border-radius: 30px;
            }

            .verticalhorizontal {
                display: flex;
                justify-content: center;
                align-items: center;
                height: 150px;
            }
        </style>
        <div class="header-h1" >
            <h1>About Us </h1>
        </div>
        <div class="container py-5">
            <ul>
                <li>Мое имя: {{ my.name }}</li>
                <ul>
                    <li>Email: {{ my.mail }}</li>
                    <li>Телефон: {{ my.phone }}</li>

                    <li><img src={{ my.imgurl }} height="150" style="margin: auto;"></li>
                </ul>
                <p style="margin-top: 50px;"></p>

                <li>Название ОП: {{ program.name }}</li>
                <ul>
                    <li>Описание программы: {{ program.description }}</li>
                </ul>
                <li>Руководитель ОП: {{ program.ruk.name }}</li>
                <ul>
                    <li>Email: {{ program.ruk.mail }}</li>
                    <li><img src={{ program.ruk.imgurl }} height="150" style="margin: auto;"></li>
                </ul>
                <p style="margin-top: 50px;"></p>

                <li>Менеджер ОП: {{ program.man.name }}</li>
                <ul>
                    <li>Email: {{ program.man.mail }}</li>
                    <li><img src={{ program.man.imgurl }} height="150" style="margin: auto;"></li>
                </ul>
                <p style="margin-top: 50px;"></p>

                <li>Друг: {{ pal1.name }}</li>
                <ul>
                    <li>Email: {{ pal1.mail }}</li>
                    <li>Телефон: {{ pal1.phone }}</li>
                    <li><img src={{ pal1.imgurl }} height="150" style="margin: auto;"></li>
                </ul>
                <p style="margin-top: 50px;"></p>

                <ul>
                    <li>Друг: {{ pal2.name }}</li>
                    <li>Email: {{ pal2.mail }}</li>
                    <li>Телефон: {{ pal2.phone }}</li>
                    <li><img src={{ pal2.imgurl }} height="150" style="margin: auto;"></li>
                </ul>
            </ul>
        </div>
    </div>

{% endblock %}

core/templates/core/answer.html
{% extends 'core/base.html' %}
{% block title %} Answer {%  endblock %}

{% block content %}
<style>
    .center-button {
        text-align: center;
    }
</style>
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl d-flex justify-content-center">
    <h1 class="mb-6 text-3xl text-center text-blue">Решили задачу!</h1>
    {% csrf_token %}
    <p class="text-center">Вы ввели следующее число: {{ question }}</p>
    <p style="margin-top: 20px;"></p>
    <div class="row justify-content-center">
        <p class="text-center">Ответ: {{ answer }}</p>
        <p style="margin-top: 35px;"></p>
        <a href="{% url 'core:task' %}"
           class="mx-auto py-4 px-8 text-lg bg-teal-400 hover:bg-teal-400 rounded-xl text-black" style="border: 2px solid grey; display: block;"  role="button">
            <button class="py-4 px-2 text-lg bg-teal-400 hover:bg-black-400 rounded-xl text-black">Введу другое число!</button>

        </a>
    </div>
</div>
{% endblock %}

core/templates/core/base.html
<!doctype html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
        <title>{% block title %}{%  endblock %} | FamMarket </title>
        <style>
            .icon {
                margin-right: 10px;
                width: 40px;
                height: 40px;
                background-image: url('https://img.icons8.com/?size=256&id=TeRvtk6Bh7uH&format=png');
                background-size: contain;
                cursor: pointer;
                background-repeat: no-repeat;
                display: inline-block;

            }
            .site-name {
                display: inline-block;
                font-size: 24px;
                font-weight: bold;
            }
        </style>
    </head>

    <body>
        <nav class="px-6 py-6 flex justify-between items-center border-b border-black-500">
            <p><a href="/" class="icon"></a></p>
            <p><a href="/" class="site-name">FamMarket</a>

            </p>

             <div class="space-x-6">
                <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">Добавить товар</a>
                <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Поиск</a>
                <a href="{% url 'core:task' %}" class="text-lg font-semibold hover:text-gray-500">Task</a>

                {% if request.user.is_authenticated %}
                    <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold border-2 border-teal-500 rounded-xl text-white bg-gray-500 hover:bg-teal-700 hover:text-gray-500">Inbox</a>
                    <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold border-2 border-gray-500 rounded-xl text-white bg-gray-500 hover:bg-gray-700 hover:text-gray-500">Dashboard</a>
                {% else %}
                    <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold border-2 border-teal-500 rounded-xl text-white bg-teal-500 hover:bg-teal-700 hover:text-gray-500">Sign up</a>
                    <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold border-2 border-gray-500 rounded-xl text-white bg-gray-500 hover:bg-gray-700 hover:text-gray-500">Log in</a>
                {% endif %}
             </div>

        </nav>
        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="px-6 py-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font semi bold text-gray-400">Скидка 10% на первую покупку</h3>
                <p class="text-lg text-gray-500">Служба поддержки работает <p>Понедельник - Воскресенье </p>
                <p class="text-lg text-gray-500">с 10:00 до 22:00</p>
                <p class="text-lg text-gray-500"> +7 (499) 000-00-00</p>
            </div>
            <div class="w-1/3">
                <h3 class="mb-5 font-semi bold text-gray-400">Полезная информация</h3>

                <ul class="space-y-2">
                    <p style="margin-top: 35px;"></p>
                    <li><a href="{% url 'core:about' %}" class="mb-5 font-semi bold text-gray-400">О нас</a></li>
                    <li><a href="{% url 'core:contact' %}" class="mb-5 font-semi bold text-gray-400">Свяжитесь с нами</a></li>
                    <li><a href="{% url 'core:privacy' %}"class="mb-5 font-semi bold text-gray-400">Наша политика конфиденциальности</a></li>
                    <li><a href="{% url 'core:terms' %}" class="mb-5 font-semi bold text-gray-400">Правила пользования</a></li>

                <footer id="colophon"> © 2024</div>
                </ul>
            </div>
        </footer>
    </body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}
{% block content %}
    <div style="text-align: center;">
        <style>
  .header-h1 {
    text-align: center;
    margin-bottom: .5rem;
  }
  .header-h1 h1 {
    display: inline-block;
    background: #0097a7;
    color: #fff;
    margin-bottom: 0;
    padding: .5rem 1rem .625rem 1rem;
    font-size: 1.5rem;
    text-transform: uppercase;
    border-radius: 30px;
  }
  .contact-info {
 font-weight: normal; /* Добавляем обычный (не жирный) шрифт */
 }
</style>

    <div class="header-h1" style="text-align: center;">
  <h1>Cвяжитесь с нами</h1>
</div>
        <div class="col" style="margin: 0 auto; width: 50%;">
            <p class="h5">Если вы не можете найти нужную информацию на нашем веб-сайте, напишите нашей службе поддержки с вашим запросом.</p>
            <p class="h5">Постарайтесь предоставить как можно больше деталей, чтобы наша команда могла быстро решить вашу проблему.</p>
        </div>

        <a href="mailto:prmuradkhanova@edu.hse.ru" target="_blank" style="display: block; margin-top: 20px;"><strong>prmuradkhanova@edu.hse.ru</strong></a>

        <p style="margin-top: 10px;"></p>

        <a href="https://t.me/muradpo" class="telegram-link" target="_blank" style="display: block;"><strong>Телеграм</strong></a>
        <p>
            <p style="margin-top: 10px;"></p>
        <a href="https://vk.com/polinamuradkhanova" target="_blank"><strong>Ссылка на ВКонтакте<strong></a>
            <p style="margin-top: 30px;"></p>
        </p>

    </div>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %} Welcome {%  endblock %}
{% block content %}
    <div style="text-align: center;">
        <style>
  .header-h1 {
    text-align: center;
    margin-bottom: .5rem;
  }
  .header-h1 h1 {
    display: inline-block;
    background: #0097a7;
    color: #fff;
    margin-bottom: 0;
    padding: .5rem 1rem .625rem 1rem;
    font-size: 1.5rem;
    text-transform: uppercase;
    border-radius: 30px;
  }
</style>
    <div class='mt-6 px-6 py-12 bg-gray-100 rounded-xl'>
        <h2 class="mb-12 text-2xl text-center">Новые товары</h2>
        <div class = 'grid grid-cols-3 gap-3'>
            {% for item in items %}
            <div>
                <a href="{% url 'item:detail' item.id %}">
                    <div>
                        <img src="{{ item.image.url }}" class="rounded-t-xl">

                    </div>
                    <div class = "p-6 bg-white rounded-b-xl">
                        <h2 class = 'text-2xl'>{{ item.name}}</h2>
                        <p class = 'text-gray-500'>Цена: {{ item.price }}</p>

                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="mt-6 flex justify-center">
            <div class="flex">
                {% if items.has_previous %}
                    <a href="?page={{ items.previous_page_number }}" class="px-4 py-2 bg-gray-200 text-gray-700">Назад</a>
                {% endif %}

                <span class="px-4 py-2 bg-gray-300 text-gray-800">{{ items.number }} из {{ items.paginator.num_pages }}</span>

                {% if items.has_next %}
                    <a href="?page={{ items.next_page_number }}" class="px-4 py-2 bg-gray-200 text-gray-700">Дальше</a>
                {% endif %}
            </div>
        </div>
        <div class='mt-6 px-6 py-12 bg-gray-100 rounded-xl'>
            <h2 class="mb-12 text-2xl text-center">Категории</h2>
            <div class = 'grid grid-cols-3 gap-3'>
                {% for category in categories %}
                    <div>
                        <a href="#">
                            <div class = "p-6 bg-white rounded-b-xl">
                                <h2 class = 'text-2xl'>{{ category.name}}</h2>
                                <p class = 'text-gray-500'>{{ category.items.count }} items</p>

                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in </h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-400 hover:bg-teal-400 rounded-xl text-black">Submit</button>
    </form>
</div>
{% endblock %}

core/templates/core/privacy.html
{% extends 'core/base.html' %}


{% block content %}
    <div style="text-align: center;">
        <style>
  .header-h1 {
    text-align: center;
    margin-bottom: .5rem;
  }
  .header-h1 h1 {
    display: inline-block;
    background: #0097a7;
    color: #fff;
    margin-bottom: 0;
    padding: .5rem 1rem .625rem 1rem;
    font-size: 1.5rem;
    text-transform: uppercase;
    border-radius: 30px;
  }
</style>


<div class="header-h1">
</div>
    <div class="header-h1" style="text-align: center;">
        <h1>Политика конфиденциальности интернет-магазина</h1>
    </div>

        <div class="col" style="margin: 0 auto; width: 50%;">
        <p class="h5">Использование Пользователем сайта означает согласие с настоящей Политикой конфиденциальности и условиями обработки персональных данных Пользователя.</p>
                    <p style="margin-top: 10px;"></p>

        <p class="h5">В случае несогласия с условиями Политики конфиденциальности Пользователь должен прекратить использование сайта.</p>
                    <p style="margin-top: 10px;"></p>

        <p class="h5">Настоящая Политика конфиденциальности применяется только к данному сайту. Администрация сайта не контролирует и не несет ответственность за сайты третьих лиц, на которые Пользователь может перейти по ссылкам, доступным на данном сайте.</p>
                    <p style="margin-top: 10px;"></p>

        <p class="h5">Администрация сайта не проверяет достоверность персональных данных, предоставляемых Пользователем сайта.</p>
                                <p style="margin-top: 30px;"></p>
            <p></p>

    </div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-400 hover:bg-teal-400 rounded-xl text-black">Submit</button>
    </form>
</div>
{% endblock %}

core/templates/core/task.html
{% extends 'core/base.html' %}
{% block title %}Task{% endblock %}
{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl d-flex justify-content-center">
    <h1 class="mb-6 text-3xl text-center" >Задача</h1>
    <form action="{% url 'core:task' %}" method="post" class="text-center">
        {% csrf_token %}
        <p>Введите число:
        </p>

        <div class="mb-3">
            {{ form.a }}
            <p style="margin-top: 20px;"></p>
        </div>
        <input class="py-4 px-2 text-lg bg-teal-400 hover:bg-black-400 rounded-xl text-black" style="border: 2px solid grey;" type="submit" value="Получить ответ"  >

    </form>
</div>
{% endblock %}

core/templates/core/terms.html
{% extends 'core/base.html' %}

{% block title %}Terms{% endblock %}
{% block content %}
    <div style="text-align: center;">
        <style>
  .header-h1 {
    text-align: center;
    margin-bottom: .5rem;
  }
  .header-h1 h1 {
    display: inline-block;
    background: #0097a7;
    color: #fff;
    margin-bottom: 0;
    padding: .5rem 1rem .625rem 1rem;
    font-size: 1.5rem;
    text-transform: uppercase;
    border-radius: 30px;
  }
</style>
        <div class="header-h1">
</div>
    <div class="header-h1" style="text-align: center;">
        <h1>Правила пользования</h1>
    </div>
        <div class="col" style="margin: 0 auto; width: 50%;">
        <p class="h5">Вы понимаете, что мы предлагаем юридические контракты, политики или соглашения, созданные и/или проверенные адвокатами или помощниками юристов для продажи через наш Сервис. </p>
                                <p style="margin-top: 10px;"></p>
            <p class="h5"> Вы признаете, что Мы не являемся адвокатами или помощниками юристов и не предоставляем юридических консультаций.</p>
                                <p style="margin-top: 10px;"></p>
            <p class="h5"> Вы признаете, что Мы не поддерживаем какого-либо конкретного адвоката или помощника юриста или какой-либо Продукт как лучший по сравнению с другим.</p>
                                <p style="margin-top: 10px;"></p>
            <p class="h5">Мы не гарантируем юридическую точность или применимость любого Продукта для ваших юридических нужд. Вы всегда будете обращаться к любому адвокату или помощнику юриста, которого вы выбрали для получения услуг, по поводу любых юридических претензий, связанных с такими услугами.</p>
                                            <p style="margin-top: 30px;"></p>
        </div>

{% endblock %}